### ISSUE TITLE
CardMarket deck Sniffer (Share)

### ISSUE THREAD

**Issue by sirrion1** [nicho92/MtgDesktopCompanion#101]
I do a decksniffer and share for if is interesting 
`package org.magic.api.decksniffer.impl;

import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;

import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import org.magic.api.beans.MagicCard;
import org.magic.api.beans.MagicDeck;
import org.magic.api.beans.RetrievableDeck;
import org.magic.api.interfaces.MTGCardsProvider;
import org.magic.api.interfaces.abstracts.AbstractDeckSniffer;
import org.magic.services.MTGControler;
import org.magic.tools.URLTools;

public class CardMarketDeckSniffer extends AbstractDeckSniffer {
	private static final String PAUPER = "Pauper";
	private static final String HIGHLANDER = "Highlander";
	private static final String URL = "URL";
	private static final String COMMANDER = "Commander";
	private static final String VINTAGE = "Vintage";
	private static final String LEGACY = "Legacy";
	private static final String MODERN = "Modern";
	private static final String STANDARD = "Standard";
	private static final String FORMAT = "FORMAT";

	@Override
	public String[] listFilter() {    
		return new String[] { STANDARD, MODERN, LEGACY, VINTAGE, COMMANDER, HIGHLANDER, PAUPER};
	}
	
	@Override
	public MagicDeck getDeck(RetrievableDeck info) throws IOException {
		logger.debug("get deck at " + info.getUrl());
		MagicDeck deck = new MagicDeck();
		deck.setName(info.getName());
		deck.setDescription(info.getUrl().toString());
		Document d = URLTools.extractHtml(info.getUrl().toString());

		Elements maincards_list = d.select(".mainboard.clearfix").select(".cardlist");
		for (Element card_list : maincards_list.select("li"))
		{
			String qte = card_list.select("span").text();
			String cardName = card_list.select(".cardName.truncate.vAlignMiddle").text();
			if (cardName.contains("//")) // for transformatble cards
				cardName = cardName.substring(0, cardName.indexOf("//")).trim();

			MagicCard mc = MTGControler.getInstance().getEnabled(MTGCardsProvider.class).searchCardByName(cardName, null, true).get(0);
			
			notify(mc);
			deck.getMap().put(mc, Integer.valueOf(qte));
		}				
	
		Elements sidecards_list = d.select(".sideboard.clearfix").select(".cardlist");
		for (Element card_list : sidecards_list.select("li"))
		{
			String qte = card_list.select("span").text();
			String cardName = card_list.select(".cardName.truncate.vAlignMiddle").text();
			if (cardName.contains("//")) // for transformatble cards
				cardName = cardName.substring(0, cardName.indexOf("//")).trim();

			MagicCard mc = MTGControler.getInstance().getEnabled(MTGCardsProvider.class).searchCardByName(cardName, null, true).get(0);
			
			notify(mc);
			deck.getMapSideBoard().put(mc, Integer.valueOf(qte));
		}			
		return deck;
	}

	@Override
	public List<RetrievableDeck> getDeckList() throws IOException {
		String url = getString(URL) + "/en/Magic/Decks/Events/Format/" + getString(FORMAT);
		logger.debug("get List deck at " + url);
		List<RetrievableDeck> list = new ArrayList<>();
		Document d =  URLTools.extractHtml(url);
		for (Element topDecks : d.select(".vAlignMiddle.latestEvents-name"))
		{		
			String eventName = topDecks.select("a").text();
			Elements topDeck = topDecks.select("select");
			for (Element option : topDeck.select("option").subList(1, topDeck.select("option").size()))
			{
				try{
					RetrievableDeck deck = new RetrievableDeck();
					
					String[] text = option.html().split("&nbsp;");
					String deckName = text[1].toString();
					if (text.length > 2) 
					{
						String author = text[2].replaceAll("[()]", "").toString();
						deck.setAuthor(author);
						
					}
					deck.setUrl(new URI(getString(URL) + "/en/Magic" + option.getAllElements().select("option[value]").val().replace(" ", "%20")));
					
					//Start Colors used in the deck this metod slows the deck list load
					Document deck_url = URLTools.extractHtml(deck.getUrl().toString());
					Elements maincards_list = deck_url.select(".mainboard.clearfix").select(".cardlist");
					StringBuilder deckColor = new StringBuilder();
					if(maincards_list.select("li").text().contains("Plain") || maincards_list.select("li").text().contains("Plains"))
					{
						deckColor.append("{W}");
					}	
					if(maincards_list.select("li").text().contains("Island") || maincards_list.select("li").text().contains("Islands"))
					{
						deckColor.append("{U}");
					}	
					if(maincards_list.select("li").text().contains("Swamp") || maincards_list.select("li").text().contains("Swamps"))
					{
						deckColor.append("{B}");
					}
					if(maincards_list.select("li").text().contains("Mountain") || maincards_list.select("li").text().contains("Mountains"))
					{
						deckColor.append("{R}");
					}
					if(maincards_list.select("li").text().contains("Forest") || maincards_list.select("li").text().contains("Forests"))
					{
						deckColor.append("{G}");
					}
					deck.setColor(deckColor.toString());
					
					//End
					deck.setDescription(eventName);							
					deck.setName(deckName);
					list.add(deck);
				}
				catch(Exception e) 
				{
					logger.error(e);
				}
				
			}
		}
		return list;
	}

	@Override
	public String getName() {
		return "CardMarket";
	}

	@Override
	public void initDefault() {
		setProperty(FORMAT, STANDARD);
		setProperty(URL, "https://www.cardmarket.com");
	}

}`

**Comment by nicho92** [comment]
Nice Job !  Thanks.
I'm looking to integrate it in next release !
