### ISSUE TITLE
MacOS Crash Report

### ISSUE THREAD

**Issue by tmccary9207** [nicho92/MtgDesktopCompanion#102]
After about half a minute this error gets logged out to the terminal.

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fff9c2dc4dd, pid=67337, tid=1295
#
# JRE version: OpenJDK Runtime Environment (14.0+36) (build 14+36-1461)
# Java VM: OpenJDK 64-Bit Server VM (14+36-1461, mixed mode, sharing, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [libobjc.A.dylib+0x14dd]  objc_msgSend+0x1d
```

**Comment by nicho92** [comment]
This problem seems to be known in the Java community. Can you try with a jvm 13?

**Comment by tmccary9207** [comment]
It works on adoptopenjdk13 it seems. Brew doesn't have an option to install JDK13 anymore. This might be something worth noting for right now. Thank you for your suggestion.
