### ISSUE TITLE
suggestion for faster entering stock

### ISSUE THREAD

**Issue by Brolmeel** [nicho92/MtgDesktopCompanion#104]
would it be possible to add keyboard shortcut key here

1. hit + to add a stock item
2. hit enter to save

![image](https://user-images.githubusercontent.com/21075655/78681999-bce61900-78ed-11ea-95c5-a6b39dd73f79.png)

**Comment by nicho92** [comment]
![image](https://user-images.githubusercontent.com/11507615/78983853-4cc1d800-7b25-11ea-8d36-f8b157f4552a.png)

**Comment by Brolmeel** [comment]
do i have to do anything to enable this? nothing happens when hitting +

**Comment by nicho92** [comment]
with Alt
