### ISSUE TITLE
cannot run the application after last update

### ISSUE THREAD

**Issue by Brolmeel** [nicho92/MtgDesktopCompanion#106]
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ magic-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 602 source files to C:\Users\c\git\MtgDesktopCompanion\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/c/git/MtgDesktopCompanion/src/main/java/org/magic/api/notifiers/impl/DorkBox.java:[9,22] package dorkbox.notify does not exist
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.451 s
[INFO] Finished at: 2020-04-09T21:24:43+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project magic-api: Compilation failure
[ERROR] /C:/Users/c/git/MtgDesktopCompanion/src/main/java/org/magic/api/notifiers/impl/DorkBox.java:[9,22] package dorkbox.notify does not exist
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by nicho92** [comment]
can you try after last update ?

**Comment by Brolmeel** [comment]
Working fine now, thanks!
