### ISSUE TITLE
Add Import/Export support for Forge deck format

### ISSUE THREAD

**Issue by allentiak** [nicho92/MtgDesktopCompanion#115]
Forge repo: https://git.cardforge.org/core-developers/forge/

**Comment by nicho92** [comment]
[test.forge.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4637986/test.forge.txt)

**Comment by allentiak** [comment]
Beware: Forge has different labels depending on the game type (Constructed - Freeform, Constructed - Commander, Draft...)

**Comment by allentiak** [comment]
E.g. compare this two implementations of the same Commander deck (XMage vs. Forge).

Forge version: [Sliver Overlord (Commander).dck.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4639156/Sliver.Overlord.Commander.dck.txt)
XMage version: [2014--Sliver.Overlord--Commander.dck.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4639158/2014--Sliver.Overlord--Commander.dck.txt)

**Comment by allentiak** [comment]
@nicho92 Thanks a lot for your hard work!
