### ISSUE TITLE
Fix Commander Forge (and XMage) deck support

### ISSUE THREAD

**Issue by allentiak** [nicho92/MtgDesktopCompanion#116]
@nicho92 Thanks for adressing #115!
However, I think it does not consider the Commander case.

Just try these two versions of the same Commander deck:
Forge version: https://github.com/nicho92/MtgDesktopCompanion/files/4639156/Sliver.Overlord.Commander.dck.txt
XMage version: https://github.com/nicho92/MtgDesktopCompanion/files/4639158/2014--Sliver.Overlord--Commander.dck.txt

**Comment by allentiak** [comment]
Sorry. I think I made a mistake here.

**Comment by nicho92** [comment]
no problemo... Xmage plugin already exist ;) and it's work.. thanks a lot for your feedback

**Comment by allentiak** [comment]
Unfortunately, it seems I was right.

Both files below are supposed to be equal (save for the lovely layout XMage embedds into the files).

A legal Commander deck in XMage is a normal deck with 99 cards in the Mainboard + 1 card (the Commander) in the SideBoard. (I know: it's ackward. But that's how it is.)

Please note that the conversion fails both ways.

Original files:
[Sliver.Overlord.Commander--Forge.dck.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4768305/Sliver.Overlord.Commander--Forge.dck.txt)
[Sliver.Overlord--Commander--XMage.dck.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4768309/Sliver.Overlord--Commander--XMage.dck.txt)

Converted files:
[Sliver.Overlord.Commander--ConvertedFromForgeToXMage.dck.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4768312/Sliver.Overlord.Commander--ConvertedFromForgeToXMage.dck.txt)
[Sliver.Overlord--Commander--ConvertedFromXMageToForge.dck.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4768313/Sliver.Overlord--Commander--ConvertedFromXMageToForge.dck.txt)

**Comment by allentiak** [comment]
Wereas I think Forge also has special tags for other constructed deck types (and I doubt XMage has, as it seems to check the validity before the actual game starts), I must say I haven't tested that functionality in any of them so far.

**Comment by nicho92** [comment]
i've updated Xmage and Forge deck import/export. let me know ;)

**Comment by allentiak** [comment]
Hi, @nicho92,

It's getting better, but it's not done yet.

Please, use the newly attached files (along with the original ones I sent before) to validate my feedback. Minor differences aside (such as line ordering, deck name conversion result, and XMage layout), the content in the pairs <"Forge", "XMageToForge"> and <"XMage", "ForgeToXMage"> should match.

Here are the defects I discovered:

-XMage importer:
--Set data for cards is lost
--First card is also lost altogether

-XMage exporter
--XMage decks have no name. It should be discarded.

-Forge importer
--Many cards get lost altogether

-Forge exporter
--It's nice that you use the original filename as deck name; that being said, the extension should be ignored for this. (Plus, the "-" maybe should be converted to (one) space?)
--Missing new line before "[Main]"
--Missing new line before "[Planes]" (in fact, I think empty sections should be ignored)

[Second.Attempt--Sliver.Overlord--Commander--XMageToForge.dck.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4782711/Second.Attempt--Sliver.Overlord--Commander--XMageToForge.dck.txt)

[Second.Attempt--Sliver.Overlord--Commander--ForgeToXMage.dck.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4782719/Second.Attempt--Sliver.Overlord--Commander--ForgeToXMage.dck.txt)

**Comment by allentiak** [comment]
As Forge has the more complex logic, I would advise you to check its deck generation code.

Specifically, the class [forge.deck.io.DeckStorage](https://git.cardforge.org/core-developers/forge/-/blob/master/forge-core/src/main/java/forge/deck/io/DeckStorage.java).

If you open the project in an IDE, it might even become easier understanding how the code works.

**Comment by nicho92** [comment]
can you send me your log files (c:/user/<name>/.magiccompanion/logs) ?

**Comment by nicho92** [comment]
-Forge exporter
--It's nice that you use the original filename as deck name; that being said, the extension should be ignored for this. (Plus, perhaps the "-" should be converted to (one) space?)
_done_

--Missing new line before "[Main]"
_done_

--Missing new line before "[Planes]" (In fact, I think empty sections should be ignored altogether.)
_done_

**Comment by nicho92** [comment]
-XMage exporter
--XMage decks have no name. It should be discarded.
__no__, i just check XmageDeckExporter.java in xmage github, deck files can contains "NAME:" and "AUTHOR:" attributes

**Comment by allentiak** [comment]
> I can't reproduce XMage importer error
> --Set data for cards is lost
> --First card is also lost altogether
>
> can you send me your log files (c:/user//.magiccompanion/logs) ?

There's no need for log :-)

Just import any of the "original" files I attached in [the fourth comment](https://github.com/nicho92/MtgDesktopCompanion/issues/116#issuecomment-643025438_), and try to export it to the other format. The output file shuold be _similar_ to the original one. You don't even need to save the deck in MTGC's format.

**Comment by allentiak** [comment]
> -XMage exporter
> --XMage decks have no name. It should be discarded.
> **no**, i just check XmageDeckExporter.java in xmage github, deck files can contains "NAME:" and "AUTHOR:" attributes

OK. _My_ mistake :-)

**Comment by nicho92** [comment]
Here is my exports. 
Import Xmage-> Export XMage to compare both files. 
same for Forge files.

I can see Forge is using "COM" for Commander extension... instead of C11.

[Sliver.Overlord.Commander--Forge2.dck.Txt](https://github.com/nicho92/MtgDesktopCompanion/files/4795125/Sliver.Overlord.Commander--Forge2.dck.Txt)
[Sliver.Overlord.Commander--Forge.dck.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4795126/Sliver.Overlord.Commander--Forge.dck.txt)
[Sliver.Overlord--Commander--XMage2.dck.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4795127/Sliver.Overlord--Commander--XMage2.dck.txt)
[Sliver.Overlord--Commander--XMage.dck.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4795128/Sliver.Overlord--Commander--XMage.dck.txt)

**Comment by allentiak** [comment]
@nicho
From the names of the files you attached, your process is not clear.
Could you please explain a few things, so I can understand what you did?
- What do names like {[Forge,Forge]2} mean?
- Which file pairs did you test?
- Which was your process for each pair? (More specifically: Which input under which conversion resulted in which output?)

**Comment by nicho92** [comment]
@allentiak , 
I import deck from Sliver.Overlord.Commander--Forge.dck.txt with . Then i export it to Sliver.Overlord.Commander--Forge2.dck.Txt . and compare both files

Same process for Sliver.Overlord--Commander--XMage.dck.txt -> Sliver.Overlord--Commander--XMage2.dck.txt

I tried to import both exported files in "Forge" and "Xmage" apps. it's OK. 

I also tried to import Sliver.Overlord.Commander--Forge.dck.txt and export it to Xmage deck. It's OK too.

Just "Commander 2011" cards are not imported from Forge, because 3 characters codename doesn't exist (CMD instead of C11).

**Comment by nicho92** [comment]
By the way, conversion is good idea, you can convert deck in the script Module (File/Script) and this content :  https://raw.githubusercontent.com/nicho92/MtgDesktopCompanion/master/src/main/resources/script/deckConverter.groovy

**Comment by allentiak** [comment]
On Fri, 19 Jun 2020 at 14:05, Nicho <notifications@github.com> wrote:

> it's OK.

It seems you've made the converter work?

Just "Commander 2011" cards are not imported from Forge, because 3
> characters codename doesn't exist (CMD instead of C11).


Maybe this is a Forge bug?

**Comment by allentiak** [comment]
@nicho92 
Hmmm... I've checking both decks I sent here, and I think I've sent two different Sliver Overlord Commander decks...

Let's try again...

These are the (XMage) decks I am trying to convert:
[2013--Slivers--Commander--(StarCity.Games).dck.XMage.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4808643/2013--Slivers--Commander--.StarCity.Games.dck.XMage.txt)
[2014--Sliver.Overlord--Commander--(Tolarian.Community.College).dck.XMage.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4808644/2014--Sliver.Overlord--Commander--.Tolarian.Community.College.dck.XMage.txt)

**Comment by allentiak** [comment]
I did a full XMage --> Forge --> XMage cycle.

Except for a few caveats, I think the conversion works quite well.

- XMage Importer:
  - If the deck has no name, don't add one (maybe use filename as name?).

-I am not sure to which filter this applies to:
-Original filename should be respected as deck name

**Comment by allentiak** [comment]
I did a full Forge --> XMage --> Forge cycle.

The exported Forge file has an little bug: it seems non-basic lands don't need the extra "|1".

[2014--Sliver.Overlord--Commander--(Tolarian.Community.College).Forge.dck.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4808670/2014--Sliver.Overlord--Commander--.Tolarian.Community.College.Forge.dck.txt)
[2014--Sliver.Overlord--Commander--_Tolarian.Community.College_.Forge2XMage2Forge.dck.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4808671/2014--Sliver.Overlord--Commander--_Tolarian.Community.College_.Forge2XMage2Forge.dck.txt)

**Comment by allentiak** [comment]
Whereas the decks are different, the conversions are full.
