### ISSUE TITLE
issue adding basic lands stock

### ISSUE THREAD

**Issue by Brolmeel** [nicho92/MtgDesktopCompanion#128]
adding basic land to stock not saved :
![image](https://user-images.githubusercontent.com/21075655/89454244-b7e08b80-d760-11ea-844f-b424a2ac7244.png)

error in log file : 

ERROR org.magic.api.dao.impl.MysqlDAO 707  - java.sql.SQLSyntaxErrorException: (conn=48) Data too long for column 'mcard' at row 1

**Comment by nicho92** [comment]
plz run this fix : https://raw.githubusercontent.com/nicho92/MtgDesktopCompanion/master/src/main/resources/script/fix-stock-mcard.groovy in script panel
