### ISSUE TITLE
issue Import Deck (wantlist) from MagicCardmarket

### ISSUE THREAD

**Issue by Brolmeel** [nicho92/MtgDesktopCompanion#132]
I go to Deck; I click Import Deck, from MagicCardMarket; I receive my WantList; then I click a list to import, but nothing is shown in Deck screen.

Debug shows a correct response from the api 

![image](https://user-images.githubusercontent.com/21075655/91412453-1d003c00-e84a-11ea-817f-ec2c45f5f714.png)

**Comment by nicho92** [comment]
Ok for me.. 
Can you send me your log file ? ( $USER_HOME/.magicdeskcompanion/logs
And can you tell me your CardsProvider (config panel)
