### ISSUE TITLE
request - sync price update in stock to MagicCardMarket

### ISSUE THREAD

**Issue by Thorgal-The-Viking** [nicho92/MtgDesktopCompanion#135]

**Comment by nicho92** [comment]
Hi,  Could you detail your request a bit?

**Comment by Thorgal-The-Viking** [comment]
If I have a card in my stock that is synced to card market to sell and I update the price in my stock, then sync again, then it creates a second copy on cardmarket and I have then 2 cards in my "offers" on cardmarket
