### ISSUE TITLE
CardShake cache server not updating these editions 

### ISSUE THREAD

**Issue by Thorgal-The-Viking** [nicho92/MtgDesktopCompanion#138]
![image](https://user-images.githubusercontent.com/70637347/93685858-77d82c80-fab2-11ea-8954-7a425e0b2cdb.png)

**Comment by nicho92** [comment]
Some extension are difficult to synchronise.. You can change your "dashboard provider" in config panel, and try to update missings sets (select them, then update selected cache).

**Comment by Thorgal-The-Viking** [comment]
I tried mtgpricers, but it was even worse

MTGGoldfish is best.
Almost all is updated now

![image](https://user-images.githubusercontent.com/70637347/93719400-9a397b00-fb82-11ea-9882-2b4ba1e8d820.png)
