### ISSUE TITLE
Alert dashboard - foil

### ISSUE THREAD

**Issue by Thorgal-The-Viking** [nicho92/MtgDesktopCompanion#141]
Alert pricing does not seem to take foiling into account?

![image](https://user-images.githubusercontent.com/70637347/97281243-8d710c80-183d-11eb-8b22-47f27b12a5e6.png)

**Comment by nicho92** [comment]
For Alert's notification it's ok. this panel is independant. But I just added a filter for PricePanel in last commit

**Comment by Thorgal-The-Viking** [comment]
if MAX in MagicCardMarket pricers config is like 20 and there are 20 non foils (with lower price ofcourse) it will not find any foils even if there are foils on MCM
