### ISSUE TITLE
request - print proxy

### ISSUE THREAD

**Issue by Thorgal-The-Viking** [nicho92/MtgDesktopCompanion#142]
could you make export deck to pdf so that it can be used to make proxies? ( correct size and high quality card pic )

**Comment by nicho92** [comment]
Yup, i already tried this with current PDFExport.... (size are editable in config panel). I'm looking for this

**Comment by nicho92** [comment]
i updated this plugin with itext 7 and try to calculate card ration in pdf. can you try and let me know ? 
(card size is now automatic, properties in config panel a now useless)

**Comment by Thorgal-The-Viking** [comment]
Hello, is there any way to set the quality of the pdf? I find that the card pictures in the scryfall cache are nice quality, but in the pdf the card (text) is kinda blurry

**Comment by nicho92** [comment]
updated. let me now with latest commit

**Comment by Thorgal-The-Viking** [comment]
yes quality is very nice now
