### ISSUE TITLE
arbitraging module

### ISSUE THREAD

**Issue by Thorgal-The-Viking** [nicho92/MtgDesktopCompanion#143]
do you have plans to make an arbitrage finance module or dashboard? seems like the program has access to all the data. For example

compare prices on tcgplayer (US) and prices on MKM (Europe). If the module could compare for example TCG buy list prices it would be nice to see potential buys in Europe and ship to US. 
I guess the most difficult again would be to find the right naming conventions on special cards like foiling, extended art, etc

**Comment by nicho92** [comment]
![image](https://user-images.githubusercontent.com/11507615/99872539-b8ebda80-2be2-11eb-8f79-31bea47f3cd6.png)

I developped a new DashLet in Dashboard. You can add both, and calculate your shopping list between 2 pricers
