### ISSUE TITLE
bug Deck Editor

### ISSUE THREAD

**Issue by Thorgal-The-Viking** [nicho92/MtgDesktopCompanion#144]
card Westvale Abbey (flipcard) is behaving strange in Deck Editor. When added it does not count as a card

![image](https://user-images.githubusercontent.com/70637347/98380254-9c7b6a00-2048-11eb-9e77-8049699c3d2c.png)

![image](https://user-images.githubusercontent.com/70637347/98380381-c9c81800-2048-11eb-861a-426f5c06f629.png)

also the card cannot be deleted from deck anymore or exported

**Comment by nicho92** [comment]
![image](https://user-images.githubusercontent.com/11507615/98387002-2d564380-2051-11eb-9784-19566c761042.png)
For me it's ok. can you explain your manipulations ?

**Comment by Thorgal-The-Viking** [comment]
restarted client, seems to work now
