### ISSUE TITLE
can mkm pricer take into account the extended art varition?

### ISSUE THREAD

**Issue by Brolmeel** [nicho92/MtgDesktopCompanion#146]
can mkm pricer take into account the extended art variation?

example : 

Vampirc Tutor extended art

![image](https://user-images.githubusercontent.com/21075655/99197886-892d7480-2795-11eb-878b-443647742030.png)

Prices are from regular version : 
![image](https://user-images.githubusercontent.com/21075655/99197906-a7937000-2795-11eb-899a-b6192db8f19f.png)

**Comment by nicho92** [comment]
Mkm API currently doesn't provide any information to distinguish the format of the cards (borderless, showcase and extanded Art).

**Comment by nicho92** [comment]
i optimized MkmPricer to check if the card is "extra" for Mkm. Then, i use this edition. But i can't validate the layout ( borderless, showcase, extended art, ...)
