### ISSUE TITLE
feature request MagicCardMarket export

### ISSUE THREAD

**Issue by Thorgal-The-Viking** [nicho92/MtgDesktopCompanion#148]
can you put extra parameter in export config for MagicCardMarket to allow to set the edition to "Any" instead of strict?

![image](https://user-images.githubusercontent.com/70637347/100017763-b4d6dd00-2ddb-11eb-92f3-41ee4992ec76.png)

so that this column says "Any" in the generated wantlist

![image](https://user-images.githubusercontent.com/70637347/100017925-e8196c00-2ddb-11eb-9164-4e37e4e4bb86.png)

**Comment by nicho92** [comment]
MKM APi is now Down until they release V3 ...
