### ISSUE TITLE
suggestion - Prices Tab

### ISSUE THREAD

**Issue by Thorgal-The-Viking** [nicho92/MtgDesktopCompanion#150]
for MKM pricer I have MAX = 20

![image](https://user-images.githubusercontent.com/70637347/104303319-3d175b80-54ca-11eb-9e19-4662514e95b9.png)

When I go to Prices Tab I will only see first 20 cards on MKM (as expected), but would it be possible to populate the table with the first 20 regular card prices and the first 20 foil prices?

For a popular card I will not see foil prices in the table because there are to many regular cards available
![image](https://user-images.githubusercontent.com/70637347/104303934-00982f80-54cb-11eb-8f00-07614f1253b6.png)

**Comment by nicho92** [comment]
Mkm API is down...waiting for new api version
