### ISSUE TITLE
empty collection after todays update

### ISSUE THREAD

**Issue by Thorgal-The-Viking** [nicho92/MtgDesktopCompanion#154]
![image](https://user-images.githubusercontent.com/70637347/105102292-274bfc80-5aaf-11eb-8584-17640ced6b66.png)

**Comment by Thorgal-The-Viking** [comment]
ERROR org.magic.api.providers.impl.MTGSQLiveProvider 504  - org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: foreign_data)

**Comment by nicho92** [comment]
Yep, SQLIve Provider is empty since mtgjson update 5.1. i opened a issue here : https://github.com/mtgjson/mtgjson/issues/758. You can use MTGJson provider instead

**Comment by nicho92** [comment]
MTGJson team fixed that issue.
You can choose SQLIve Provider and set "FORCE_RELOAD" to true and restart app. 
![image](https://user-images.githubusercontent.com/11507615/105338880-557b2a80-5bdc-11eb-9d61-5108f5d4ed1f.png)

**Comment by Thorgal-The-Viking** [comment]
ok thanks, its working again
