### ISSUE TITLE
Execution error: Cannot invoke "org.magic.api.interfaces.MTGCardsProvider.init()"

### ISSUE THREAD

**Issue by allentiak** [nicho92/MtgDesktopCompanion#167]
When executing, I get the following error:
```
java.lang.NullPointerException: Cannot invoke "org.magic.api.interfaces.MTGCardsProvider.init()" because the return value of "org.magic.tools.MTG.getEnabledPlugin(java.lang.Class)" is null
	at org.magic.api.main.MtgDesktopCompanion.<init>(MtgDesktopCompanion.java:55)
```

Please see sceenshot below:
![MTG Companion error--Screenshot from 2021-06-06 17-38-28](https://user-images.githubusercontent.com/1922297/120939395-43fb7080-c6ee-11eb-83e1-5f3c91d9ca83.png)

[full debug log (for local master build)](https://github.com/nicho92/MtgDesktopCompanion/files/6604901/debug.log)

Tested on Java 15 on Debian "testing", both versions 2.25 (both local build and official release) and master (local build on current master - 5003ca9ef5d78f5cece2bc0612360aa5c703de7e).

_(Important: I haven't run the script mentioned in the release page, simply because I don't know exactly when should I do so.)_

**Comment by nicho92** [comment]
Hi, 
can you open /<user>/.magicDeskCompanion/mtgcompanion-conf.xml and check if you have a provider to "true".

 <providers>
    <provider>
      <class>org.magic.api.providers.impl.PrivateMTGSetProvider</class>
      <enable>false</enable>
    </provider>
    <provider>
      <class>org.magic.api.providers.impl.ScryFallProvider</class>
      <enable>false</enable>
    </provider>
    <provider>
      <class>org.magic.api.providers.impl.MTGSQLiveProvider</class>
      <enable>**true**</enable>
    </provider>
    <provider>
      <class>org.magic.api.providers.impl.Mtgjson5Provider</class>
      <enable>false</enable>
    </provider>
    <provider>
      <class>org.magic.api.providers.impl.MagicTheGatheringIOProvider</class>
      <enable>false</enable>
    </provider>
  </providers>

**Comment by allentiak** [comment]
Thanks for the pointer!

From what I see, the only provider I had enabled in the config file was obsolete.
I only had `org.magic.api.providers.impl.Mtgjson`**4**`Provider` enabled.

I tried enabled `org.magic.api.providers.impl.MTGSQLiveProvider` and it worked!

After the program started, it automatically updated MTGJSON's version to 5.

**Comment by allentiak** [comment]
(Whereas your answer did solve my problem, I haven't closed this only because I'm not sure whether this manual fix would require an update from your end. I leave this up to you)

**Comment by nicho92** [comment]
Hi, no problem, thanks for your feedbacks. I've no feedback like this one... maybe a missclick/bug... 

> (Important: I haven't run the script mentioned in the release page, simply because I don't know exactly when should I do so.)

If you are using 2.25 from a previous setup, you can launch  it now . It will update JsonServer and HttpServer plugin.

**Comment by allentiak** [comment]
> Hi, no problem, thanks for your feedbacks. I've no feedback like this one...

No problem. I know that, without reproducibility information, it becomes very difficult for you to help others back...


> > (Important: I haven't run the script mentioned in the release page, simply because I don't know exactly when should I do so.)
> 
> If you are using 2.25 from a previous setup, you can launch it now . It will update JsonServer and HttpServer plugin.

Done. Thanks.
