### ISSUE TITLE
Add Challenger decks to 'Sealed products'

### ISSUE THREAD

**Issue by Ads20000** [nicho92/MtgDesktopCompanion#169]
[The Challenger decks](https://magic.wizards.com/en/articles/archive/feature/challenger-decks-2021-02-12) seem to be missing from the 'Sealed products' section, please could they be added?

MTG Companion v2.25 (OpenJDK 16, Ubuntu 20.10)

**Comment by nicho92** [comment]
item is added in MTGCompanion. 
Now need to search items on web (set, pictures, ...)
