### ISSUE TITLE
View list of cards in main collections panel?

### ISSUE THREAD

**Issue by muff1nman** [nicho92/MtgDesktopCompanion#17]
Is there a way to view the list of cards in my library in the main collections panel? Further can one use sort/filter parameters on that panel? The upper right library collections list is nice, but seems like it would be quite unweildly for large collections.

**Comment by nicho92** [comment]
You can view your collection in Search panel (combobox : Collections), and play with sort and filters.
I've just fix it in ebd7809  (large collection wasn't displayed).

but i'm ok to think about this view in collection panel.

I use the tree collection with 27000 cards. Navigation is pretty good
