### ISSUE TITLE
Sidebar resize glitches

### ISSUE THREAD

**Issue by Ads20000** [nicho92/MtgDesktopCompanion#170]
The left-hand-side sidebar glitches, see video demonstration.

The recording is of Oracle JDK 16 (Ubuntu 20.10) but this also applies to OpenJDK 16 (Ubuntu 20.10)

https://user-images.githubusercontent.com/3178485/123557018-67ae5580-d786-11eb-81f9-a1ebebac293a.mp4

**Comment by nicho92** [comment]
Hi, i see you're using Gnome Layout, can you tell me if you have the same beavior with other LookAndFeel ? 
![image](https://user-images.githubusercontent.com/11507615/123619162-34f97100-d809-11eb-978c-9736db73744e.png)

**Comment by Ads20000** [comment]
Nimbus works fine so assume this is a bug with the GTK Look.

**Comment by nicho92** [comment]
ok thanks. certainly a bug with this LookAndFeel... can't do anything...
