### ISSUE TITLE
Collections - Worldwake

### ISSUE THREAD

**Issue by SpaceMageDoge** [nicho92/MtgDesktopCompanion#173]
When clicking to view Worldwake through the collection tab, the window does not populate with its respective set list. Was on 2.24, updated to 2.25 and the issue persisted.

**Comment by nicho92** [comment]
can you send me your log file in /<user>/.magicDeskCompanion/logs ? 

only for this set ?

**Comment by SpaceMageDoge** [comment]
[mtgcompanion.log](https://github.com/nicho92/MtgDesktopCompanion/files/6836811/mtgcompanion.log)

The only one that I've noticed. I can go through them one by one and report back any others a find a little later.

**Comment by nicho92** [comment]
let me now if this error persist with latest release.

**Comment by SpaceMageDoge** [comment]
Innistrad, Rise of the Eldrazi, Scars of Mirrodin are working on 2.26
