### ISSUE TITLE
Web UI Server error

### ISSUE THREAD

**Issue by JulienSambre** [nicho92/MtgDesktopCompanion#176]
Hi!

When using the web ui server, I am able to see the list of decks that I have import in MtgDesktopCompanion, but when I click on the deck, the fields are empty. The root cause seems a call to the json backend which respond 500 :

![image](https://user-images.githubusercontent.com/14327288/127122799-d910213d-2391-49c3-93de-2db2fd447e8a.png)

![image](https://user-images.githubusercontent.com/14327288/127122836-be1f85ef-f940-408e-a09e-53313b958a48.png)

**Comment by JulienSambre** [comment]
Find the bug : it works when there is no space in the name of the deck ("Merfolk" for example) and the page bug when it has space in the name of the deck ("Abzan Dina Sisters" for example).

I found out that if I fix the URL manually "/pages/deck.html?name=Abzan Dina Sisters" -> "/pages/deck.html?name=Abzan_Dina_Sisters" it fix the problem.

**Comment by JulienSambre** [comment]
More precisely : when you add a new deckto MtgDesktopCompanion, it saves the deck's name with space, but save the json file with "_" in the filesystem.

Then, Web UI can't find the right file (it search a file with space, like the logical deck name). If you replace the json filename with the logical one (with space), it works.

I think it should save somewhere a link between the logical name of the deck and the technical one.

**Comment by nicho92** [comment]
Hi Julien,

Next release (2.26) will fix it by removing the file storage of decks. I'll
store them in the selected database. More secure .

**Comment by JulienSambre** [comment]
Nice! Thanks :).
