### ISSUE TITLE
Web UI, bug with sideboard cards

### ISSUE THREAD

**Issue by JulienSambre** [nicho92/MtgDesktopCompanion#177]
Hi!

When there is cards in the sideboard, the UI breaks and do not show any stats, and no cards appears when select "Side" tab : 

![image](https://user-images.githubusercontent.com/14327288/127296863-455d9b6c-d62d-46af-9b52-5a37757588a8.png)

I see in the console, the following error : 

TypeError: row.rarity is undefined

**Comment by nicho92** [comment]
rarity field has been removed from Object in backOffice. You need to update your deck and/or reimport it with latest released
