### ISSUE TITLE
WebUIServerLauncher not running : java.lang.ClassNotFoundException: org.magic.api.main.WebUIServerLauncher

### ISSUE THREAD

**Issue by JulienSambre** [nicho92/MtgDesktopCompanion#178]
Hi!

I just got the last release (2.26), but when I want to launch the WebUIServerLauncher (may it be with web-ui.bat or web-ui.sh), I got the following exception : 

```
Error: Could not find or load main class org.magic.api.main.WebUIServerLauncher
Caused by: java.lang.ClassNotFoundException: org.magic.api.main.WebUIServerLauncher
```

**Comment by nicho92** [comment]
hoppsy my bad... i forgot to change theme with new release. 

here is new files to replace : 
[web-ui.bat.txt](https://github.com/nicho92/MtgDesktopCompanion/files/7007739/web-ui.bat.txt)
[web-ui.sh.txt](https://github.com/nicho92/MtgDesktopCompanion/files/7007740/web-ui.sh.txt)
