### ISSUE TITLE
Setting Stock card Collection as Library doesn't update Library Collection

### ISSUE THREAD

**Issue by Ads20000** [nicho92/MtgDesktopCompanion#180]
MTG Companion v2.26

Steps to reproduce:

1. Deck -> Create new deck -> Add a card to the deck -> Click on the card in the deck -> Click 'Add cards in stocks'
2. Stock -> Reload -> Change the Collection value of the card you added to 'Library' -> Save in batch -> Reload
3. Collections -> Refresh collections -> Library -> observe that the card has not been added to your Library on the Collections screen

I'd expect the Collections screen to update when I reload it as I have added cards to it via the Stock screen...?

[mtgcompanion.log](https://github.com/nicho92/MtgDesktopCompanion/files/7070796/mtgcompanion.log)

**Comment by nicho92** [comment]
Hi, there is only sychronization Collection -> Stock. If you want to add Stock Item in your collection you can import it from collection (right click on choosen collection, and "import from stock" 
![image](https://user-images.githubusercontent.com/11507615/131224504-b2041483-fb1f-4a42-80f4-07f74a066c57.png)

**Comment by Ads20000** [comment]
Excellent this isn't a bug then, thanks for aiding my understanding of the workflow in MTG Companion :)
