### ISSUE TITLE
Client not adding cards to collection

### ISSUE THREAD

**Issue by SpaceMageDoge** [nicho92/MtgDesktopCompanion#185]
2.26 does not seem to add cards selected from the collections window using the import collection button. Using 2.25 works without issue. Attached is the log file.
[mtgcompanion.log](https://github.com/nicho92/MtgDesktopCompanion/files/7190456/mtgcompanion.log)

**Comment by nicho92** [comment]
Hi, 

you should run this script after install new version : 
https://raw.githubusercontent.com/nicho92/MtgDesktopCompanion/master/src/main/resources/script/script-2.25.groovy
and
https://raw.githubusercontent.com/nicho92/MtgDesktopCompanion/master/src/main/resources/script/script-2.26.groovy
