### ISSUE TITLE
In stock screen going to Prices tab programs hangs

### ISSUE THREAD

**Issue by Thorgal-The-Viking** [nicho92/MtgDesktopCompanion#193]
log file loops like this : 

![image](https://user-images.githubusercontent.com/70637347/139506175-00ef1561-4b0b-40df-bee2-1daaa1bd9fea.png)

**Comment by nicho92** [comment]
HI, can you send me more information about your configuration ( dao ? provider ? ) ? and you behavior (where did you click) ? or send me your full log.

**Comment by Thorgal-The-Viking** [comment]
It happens when I click on the prices tab.
I am using MariaDB

![image](https://user-images.githubusercontent.com/70637347/139538484-cb21fb13-3f89-4574-9a3c-e5fa6550b583.png)

**Comment by nicho92** [comment]
cause of CardKingdom pricer :/ it's verrrrrrrrrry long sometimes... i'm looking for the reason
you can't deselect it from pricers configuration
