### ISSUE TITLE
Collection screen numbers

### ISSUE THREAD

**Issue by Thorgal-The-Viking** [nicho92/MtgDesktopCompanion#198]
Numbers in collection screen do not seem correct anymore

ex I have cards from Innistrad Midnight Hunt and also from Midnight Hunt Commander; yet numbers show zero : 

![image](https://user-images.githubusercontent.com/70637347/142161639-130c7155-0c9e-4b92-b8a4-99e67ae1c680.png)

**Comment by nicho92** [comment]
Hi,

which do you use ?

**Comment by Thorgal-The-Viking** [comment]
MariaDB (mysql)

**Comment by nicho92** [comment]
For me it's ok.

can you check which collection did you add your cards, and check your main library in config/Config/Main collection value.

**Comment by Thorgal-The-Viking** [comment]
needed to do "load from stock" to update collection
