### ISSUE TITLE
Card art versions

### ISSUE THREAD

**Issue by Arkewas** [nicho92/MtgDesktopCompanion#200]
**Configuration **
 - DAO: 
 - Cards Provider:  Slightlymagic
 - OS: [e.g. iOS] : Windows 10
 - Version [e.g. 22]: MTG Companion 2.28

**Describe the bug**
Hello, I have downloaded MTG card pictures from https://mega.nz/folder/4gIQTabQ#PFrnkeYbRmlrgf2swxWz1Q
I have put them in subfolders for each set but for the cards with different card arts only the original art is shown.
For example the Acclaimed Contender card (Throne of Eldraine expansion); the jpg files are properly named Acclaimed Contender1.fullborder.jpg and Acclaimed Contender2.fullborder.jpg but the alternate card image is the same as the original one as you can see from the attached screenshot. The same issue occurs with all cards with different card arts.
Am I missing something?
Best regards

**Screenshots**
![MTG Companion issue with different card arts](https://user-images.githubusercontent.com/85570370/144630177-925280f2-ed5b-4bcb-8825-82b9e3c9652e.jpg)

**Comment by nicho92** [comment]
I fixed for next release. but all case are not covered
If you have a naming convention somewhere....( with all altered card name - borderless, showcase, extended ARt, ....).

**Comment by Arkewas** [comment]
Thank you for fixing that but do you mean I have to rename the alternate jpg files differently from (Card name)2.fullborder.jpg ?
If this is the case, which is the exact naming convention to match MTG Companion database for Alternate Art, Extended Art, Showcase, Borderless etc. ?
In the above example the 2nd cart art for Acclaimed Contender is Extended Art; I have renamed the file as Acclaimed Contender (Extended Art).fullborder.jpg but it still doesn't work.

Best regards

**Comment by nicho92** [comment]
You don't have to rename them don't worry :p
The app will check it by itself.

I did this quick fix but I think it's not optimized.  i have no detail of
naming convention if there are "Showcase" , " extended art " and normal
card in the same set.

**Comment by Arkewas** [comment]
Thank you for the clarification; I'm eager to test 2.29 version. Can you tell me when it will be released approximately?

Best regards

**Comment by nicho92** [comment]
maybe at end of january. Otherwise, you can compile the source from git with maven

**Comment by Arkewas** [comment]
Very well, I'll wait for the official 2.29 release

Best regards
