### ISSUE TITLE
Minor Webshop issues

### ISSUE THREAD

**Issue by bewarellamas** [nicho92/MtgDesktopCompanion#210]
Version:  2.30

Have some small webshop issues to report. I have the site up if needed. [](http://fridgewire.com)
Not urgent, just wanted to get them documented somewhere.

1. **RESOLVED** Have the option to not show sealed product, but the link for sealed product shows when in the "Needed" page. (Also just found it shows on the My Account page)
![image](https://user-images.githubusercontent.com/97301098/151997620-63b186d2-0945-4119-9267-f214a3aeaef0.png)
![image](https://user-images.githubusercontent.com/97301098/151997828-7bade0db-43fc-4110-acd0-24edcb9cdcec.png)

2. **RESOLVED** In the "My Account" page under My Orders the Status header is misspelled to statut.
![image](https://user-images.githubusercontent.com/97301098/151998396-b3c3004c-7f54-4356-a075-53b240fbd518.png)

3. When using the search bar at the top of the page pressing Enter just reloads the page instead of submitting the search. Pressing the magnifying glass makes if function properly.

4. **RESOLVED** Opening the Top Product selector and closing it without selecting a card causes a new card with an index of -1 to be saved to the mtgcompanion-conf.xml file. This causes most of the GUI to crash with a NullPointerException as the stock returns null. Can be manually resolved by editing the xml to remove that entry.
![image](https://user-images.githubusercontent.com/97301098/152000741-b27103bf-2d88-4018-8325-a9fc9bcb0fb4.png)

5. **RESOLVED** This is more of an enhancement request and very very minor. The "Searched Product" header is a little misleading and doesn't really convey the meaning intended (I think). Something like Needed Cards/Product may be more clear.

6. **NOT AN ISSUE** Not sure if anything can be done, but the page load is really slow with a large collection (I have 6500 items in the selling library). Optimization is likely far off and that is fine. I just wanted to mention that. It also could be related to the network setup I have (hosting from a desktop through a home router so not designed for that kind of traffic). **DISREGARD. I checked resource monitor and the Json requests are only taking about a second, but it is maxing out my other resources. This is with my device.**

**Comment by nicho92** [comment]
point 2. is fixed

**Comment by nicho92** [comment]
Poinnt 1. is fixed

**Comment by nicho92** [comment]
Point 5. is fixed

**Comment by nicho92** [comment]
Point 6. "updated"... results are stored in cache.. but i optimized the query for one call instead of two.

**Comment by nicho92** [comment]
@bewarellamas  can you pull latest commit and let me know ? ( i added some function on the shop like prices range and sort)

**Comment by bewarellamas** [comment]
I pulled it down and it looks like it is working. I will test it more when I have time.  I will keep the website up if needed for testing 
http://fridgewire.com

**Comment by nicho92** [comment]
ok thanks. it's still too long ( Btw, you should up the Cache Time in Json Server to >1 min)

**Comment by bewarellamas** [comment]
Changed the settings you suggested and it is actually MUCH faster. Thank you. Also tested my last point and that seems to be working. Closing these issues.
