### ISSUE TITLE
Web server

### ISSUE THREAD

**Issue by nyteghost** [nicho92/MtgDesktopCompanion#223]
I can't seem to find a server config to change ports, or anything. Is there a guide on how to setup for web access?

**Comment by nicho92** [comment]
Hi, 

you have configuration parameters in : 
Configuration/Plugins/Servers

![image](https://user-images.githubusercontent.com/11507615/164988054-5128c2ae-bb3f-418c-9691-e9be0db51a0c.png)

**Comment by nyteghost** [comment]
I am attempting to run it on headless Linux. I have just started getting into Linux. What would be the folder path for the chnsges to be made to? I'll get the actual error when I get home, but I think it is from ports. I was getting a w11 error I think? When I get home, I'll post the actual error.

**Comment by nyteghost** [comment]
Or. Better yet, have you attempted to run MTG on heroku?

**Comment by nyteghost** [comment]
- Decided to switch it over to windows. Easier time for me.

**Comment by nicho92** [comment]
By default, Linux doesn't allow opening port 80 ... maybe by changing port to something like 8080 or else.. can you send me your linux log ?
