### ISSUE TITLE
Draw probabilities need no card split by Edition

### ISSUE THREAD

**Issue by shithead** [nicho92/MtgDesktopCompanion#233]
merge cards with same name to one probability.

E.g. Mountains from different editions can merge his draw probabilities.

**Comment by nicho92** [comment]
can you show me a screencap of the error ? You mean mountain from differents sets are are not merged ? 
![image](https://user-images.githubusercontent.com/11507615/191902129-8f86cb21-8b99-4b37-9b6e-f66753279e76.png)

**Comment by nicho92** [comment]
ok i see

**Comment by nicho92** [comment]
We should update DrawProbabilityPanel.initDeck() function, and build a "dynamic" model with correct cards count... i'm working on it ;)

**Comment by shithead** [comment]
okay i work on some code like this.

```java
public class MagicDeck implements MTGStorable {
 
 
 
 public MagicDeck getMergedDeck() {
   // found double named cards
   // get count of cards
   // int getCardCountByName(cardName);
   // set new Deck without edition information

   List<MagicCard> mergeCardList = new ArrayList<MagicCard>();
   List<String> cardNames = new ArrayList<String>();
   for ( MagicCard mc : getUniqueCards() ) {

     if (cardNames.contains(mc.getName())) {
       Optional<MagicCard> anyCards = getMainAsList().stream().filter(k->k.getName().equalsIgnoreCase(mc.getName())).findAny();
       for (; anyCards.isPresent(); anyCards.get()) {
         mergeCardList.add(mc);
       }
       cardNames.add(mc.getName());
     }
   }

   MagicDeck mergedDeck = toDeck(mergeCardList);
   mergedDeck.setName("merged cards deck");
   return mergedDeck;
 }
```

but i get an outofbound. sorry im not good in java.

**Comment by shithead** [comment]
so this code get the right cards back, but  i still get a java.lang.ArrayIndexOutOfBoundsException

**Comment by shithead** [comment]
now its work, here my diff 
[draw_probability.diff.txt](https://github.com/nicho92/MtgDesktopCompanion/files/9653116/draw_probability.diff.txt)
