### ISSUE TITLE
can't delete card from sideboard via contextmenue

### ISSUE THREAD

**Issue by shithead** [nicho92/MtgDesktopCompanion#236]
**Configuration **
 - OS: nixos-22.05
 - Version 2.36

**Describe the bug**
If I add a Card to Sideborad, it is not able to delete them via contextmenue. I get no error or debug information in log.
Workaround: send this card to maindeck and delete it from there.

**Comment by nicho92** [comment]
only on sideboard ? no problem with mainboard ?

**Comment by shithead** [comment]
yes mainboard is ok.
