### ISSUE TITLE
deckbuild can't decrease number of card on main and sideboard

### ISSUE THREAD

**Issue by shithead** [nicho92/MtgDesktopCompanion#242]
**Configuration **
 - DAO: SQLIte
 - OS: nixos-22.05
 - Version future release 2.37 (current master [2ce2c61](https://github.com/nicho92/MtgDesktopCompanion/commit/2ce2c617d59575b58d1a1f17e97baf61605e7094))

**Describe the bug**
I'm not able to decrease number of card in main and sideboard panel via down arrow.

**Comment by nicho92** [comment]
![image](https://user-images.githubusercontent.com/11507615/230948208-cd2addf9-8398-4287-acde-d8f53c483487.png)
it works for me ... can you explain your bug ?
