### ISSUE TITLE
Woocommerce Export Error

### ISSUE THREAD

**Issue by dean2cool4u** [nicho92/MtgDesktopCompanion#254]
**Configuration **
 - OS: Windows 10
 - Version: 2.39

Hey, getting a error when trying to export my stock to woo commerce for a WordPress site I'm building. I have some screenshots for you if you would like to see them. I am a Technical lead but I write 100% of the time in C# so java is new to me. But i did my best to track down the issue. 

CMD Error:
![image](https://user-images.githubusercontent.com/6098858/230729552-a2c5db42-ee2e-4dad-bec4-1146c8aa3f60.png)

Found the file with the issue (I believe this is it)
MtgDesktopCompanion-Master\src\main\java\org\magic\api\exports\impl\WooCommerceExport.java

In eclipse for some reason the for loop is returning null json values. If this was C# I could breakpoint it and walk through it but like I said im new to Java. Hope this helps. 
![image](https://user-images.githubusercontent.com/6098858/230729746-d8674a0a-f437-4ba8-a54b-78bb637ce36f.png)

**Comment by nicho92** [comment]
Hi @dean2cool4u . thanks for your investigation. I'm lookinf for this bug.
By the way .. is it possible to get a sandbox access (in private) ? it could be helpful for debugging

**Comment by dean2cool4u** [comment]
Like access to my computer? Because no that won't happen. Going to watch some tutorials on how to compile and breakpoint java. If I find anything or fix the issue I'll report back.

**Comment by nicho92** [comment]
an access to your wooCommerce backoffice ;) not your computer

**Comment by dean2cool4u** [comment]
So i have the MtgDesktopCompanion-master solution open and i am trying to right click on it and debug as a  java application. When i do I get confronted with a  selection screen (see image). Which option do i choose? 
![image](https://user-images.githubusercontent.com/6098858/230799053-3507b7d6-9a3b-4c0f-83d5-009522152faa.png)

**Comment by nicho92** [comment]
org.magic.main.MtgDesktopCompanion
