### ISSUE TITLE
Deckbox REGEX not matching default export

### ISSUE THREAD

**Issue by bewarellamas** [nicho92/MtgDesktopCompanion#255]
Tested with current release. Reported on discord

The default DeckBox csv export is including two new columns at the end named "Printing Id" and "Printing Note". It appears the REGEX is missing these entries. The correct CSV headers are below.

`Count,Tradelist Count,Name,Edition,Card Number,Condition,Language,Foil,Signed,Artist Proof,Altered Art,Misprint,Promo,Textless,Printing Id,Printing Note,My Price`

A workaround it to delete the "Printing Id" and "Printing Note" columns from the CSV file.

**Comment by nicho92** [comment]
Until next release, put (\d+),(\d+),((?=")".?"|.?),(.?),(\d+)?,(.?),(.?),(foil)?,(signed)?,(proof)?,(altered)?,(misprint)?,(promo)?,(textless)?,(.?),(.*?),$(\d+(.\d{1,2})?) in REGEX for DeckBox plugin.  Next release will embedded the regex online for better maintenance
