### ISSUE TITLE
Add scaling option for artwork in collections tab

### ISSUE THREAD

**Issue by r-nd-m** [nicho92/MtgDesktopCompanion#263]
Currently, artwork in the collections tab has a fixed size - with large screens and high quality artwork it would be beneficial to add scaling option - so the artwork can be viewed as bigger up to the native size.

**Comment by nicho92** [comment]
Hi, you can change thumbnail size in config panel 
![image](https://github.com/nicho92/MtgDesktopCompanion/assets/11507615/8c7edfc1-9aeb-4429-8c40-0cf9be376f7a)
let me know ;)

**Comment by r-nd-m** [comment]
I tried it but doesn't seem to affect the artwork - but I don't know whether we're talking about the same place, I mean this:
![image](https://github.com/nicho92/MtgDesktopCompanion/assets/12116577/e050f3df-d901-47cb-8c5a-66f8367fe16f)
