### ISSUE TITLE
Cannot add set with token only to collection

### ISSUE THREAD

**Issue by ampotos** [nicho92/MtgDesktopCompanion#283]
Hi,

I'm just starting using MtgDesktopCompanion to manage my MTG collection.

I also have some promo token and art card like the ones in the sets "Phyrexia: All Will Be One Art Series" and "One Japanese Promo Tokens".
But I cannot add them to my collection, I guess that's because this sets have 0 cards and the collection doesn't includes the cards listed as tokens.

It would be nice if there were a way to also include these sets and the tokens from the normal sets.

**Comment by nicho92** [comment]
Hello, it is already possible to add tokens/art to your stock.  However, I see, in some cases, there are errors. Can you confirm the database you are using? Furthermore, I will optimize the interface a little to make the operation simpler.

**Comment by ampotos** [comment]
I'm currently using SQLite.
