### ISSUE TITLE
Adding a option to detach decklist as a on-top resizeable and moveable pinned window

### ISSUE THREAD

**Issue by Arkewas** [nicho92/MtgDesktopCompanion#293]
Hello,
I'm a MTG Arena player and I'm glad that MTG Companion supports MTG Arena decks' format for importing. As you can see from the attached screenshot the decklist is barely visible but adding a option to detach the decklist as a single window that you can pin on top, resize and move around the screen would solve the issue.

![MTG Companion decklist](https://github.com/user-attachments/assets/549cbffe-1560-418e-a248-261af64c1cbb)

**Comment by nicho92** [comment]
Hi @Arkewas i'm OK with this new option.
One interesting tips for you, consider changing the dimensions of the image preview to have more space for the deck list table. It's in the configuration / GUI menu ;)

**Comment by nicho92** [comment]
What are your current dimension ? i'm in 171x237 in my configuration. and i've enought space to get the entire table

**Comment by Arkewas** [comment]
In GUI configuration I've set thumbnail size is 460 x 639. I must add that MTG Companion has a lot of option and furthermore is free software (anyway I'm considering to make a donation to support your work). Do you have though to add your software to CCGHQ website to make it known to a wider audience ? https://www.slightlymagic.net/forum/viewforum.php?f=20&sid=dc53cee9e2f25aa36c3af46a38b4e5c8  I think you have to contact CCGHQ Admin to do it.

**Comment by nicho92** [comment]
thanks for your feedback, i appreciate it. 
I never took the time to advertise the application... I'm bad at sales (even for a free product).

I'll do it in a near futur :)
