### ISSUE TITLE
MongoDB Auth Methods & Object Serialization

### ISSUE THREAD

**Issue by wizcreations7** [nicho92/MtgDesktopCompanion#301]
# Overview
Hey there! I've been trying to get your app working with MongoDB 7.0 and ran into some authentication challenges. It's been causing issues with loading UI elements.

Did a little bit of digging to see if I could find a solution, and provide a pull request, but things are a bit bigger than the rather simple issue I thought it might've been. Here's what I've found so far.

# What Happened
The app's hitting a series of authentication errors that seem to stem from MongoDB 7.0's security changes. Here's the progression:

### First Try
Initial connection attempt failed due to authentication method mismatch:

```log
com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='MTG', source='mtgdesktopcompanion', password=<hidden>, mechanismProperties=<hidden>}
```

MongoDB 7.0 requires SCRAM-SHA-256, but the DAO is defaulting to SCRAM-SHA-1.

### Second Try
Updated to SCRAM-SHA-256, but encountered a database source issue:

```log
com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='MTG', source='mtgdesktopcompanion', password=<hidden>, mechanismProperties=<hidden>}
```

After this, I also found that the DAO is attempting authentication against **mtgdesktopcompanion** instead of the expected **admin** database.

### Third Try
Updated arguments to authenticate against **admin**. 

Authentication problems seem to be solved (up to this point) with this fix, however a new object serialization error still prevents the application from loading.

# Current Situation
Authentication issues now aside, I believe there's a deeper problem with object serialization than there was with authentication:

![image](https://github.com/user-attachments/assets/acbf6b82-2bbe-4ec9-a450-92c489e4f239)

The POJO codec configuration isn't handling **MTGCollection** and **ImageIcon** objects properly. I haven't done enough digging around to say this is the core issue. But, after looking a bit closer at `MongoDbDAO.java`, there are a few other areas that could probably use attention. 

**Big things**:
1. Authentication mechanism isn't version-aware
2. Connection string construction could probably be more robust
3. POJO serialization needs better handling for UI components

Hopefully this helps you with diagnosing the core and finding a fix. If you need it, I'm happy to help test any changes and provide additional logs.

Cheers!

*Side note: Apologies if any part of this is inaccurate. I'm rusty with Java.*

**Comment by nicho92** [comment]
Hi wiz . Thanks for your works . 

1. Can you tell me you current version ? or did you pull latest commit ? 
2. Are you using local MongoDB ? or Online ? (atlas). In this case i can't reproduce error.

**Comment by nicho92** [comment]
I think it's a small add on MTGCollection bean (MTGIconable interface)... now MongoClient try to serialize getIcon() function but it's not necessary

**Comment by wizcreations7** [comment]
> Hi wiz . Thanks for your works .
> 
> Can you tell me you current version ? or did you pull latest commit ?

Of course! I try to help where I can.

I am currently running off the latest release.
