### ISSUE TITLE
Adding AetherHub to External File Format importing to the stock

### ISSUE THREAD

**Issue by Arkewas** [nicho92/MtgDesktopCompanion#304]
Hi Nicho,

would it be possible to add support for AetherHub CSV file when importing to the stock ? Below you can find a sample of the CSV file I've exported from AetherHub website.

Count,Tradelist Count,Wishlist Count,Name,AetherHub Card Id,Set Code,Card Number,Multiverse Id,Mtgo Id,Scryfall Id,TCGplayer Id,Cardmarket Id,Condition,Language,Foil,Signed,Artist Proof,Altered Art,Misprint
4,0,0,Mind Stone,11834,WTH,153,4436,9135,162e81d3-6cd4-4cb8-8ed8-cfbd8d34ca71,,,NearMint,English,0,0,0,0,0
1,0,0,Worn Powerstone,74602,HA7,13,,,5227c107-04e7-4d7e-83d4-9d38c723b816,,,NearMint,English,0,0,0,0,0
3,0,0,Ancestral Mask,19639,MMQ,229,19634,13491,1203f98a-fb6e-4f16-88e3-553eba177450,,,NearMint,English,0,0,0,0,0
1,0,0,Captain Sisay,24674,INV,237,25976,14717,d24d441c-f37f-44fe-8a93-f5c89df807e4,,,NearMint,English,0,0,0,0,0
1,0,0,Putrid Warrior,29535,APC,117,26758,16334,17fce298-3338-4f41-8156-ab6322951a76,,,NearMint,English,0,0,0,0,0
2,0,0,Terravore,17342,ODY,278,29982,16555,c39c412b-2f21-483a-b744-5d55bc007c0d,,,NearMint,English,0,0,0,0,0
1,0,0,Burden of Guilt,27543,DKA,4,262873,43459,d7440288-6c55-4502-bf20-3c5b50a2de5a,,,NearMint,English,0,0,0,0,0
2,0,0,"Avacyn, Angel of Hope",29053,AVR,6,239961,43823,ba149706-cd17-4da6-8403-ccfe2d6cb437,,,NearMint,English,0,0,0,0,0

**Comment by Arkewas** [comment]
Thank you for adding AetherHub CSV import to MTG Companion.

**Comment by nicho92** [comment]
import / export stock OK.
