### ISSUE TITLE
Comment builder ce projet sous linux

### ISSUE THREAD

**Issue by tturlin** [nicho92/MtgDesktopCompanion#50]
Bonjour,
Je suis nouveau sous linux, et joueur de magic depuis un certain temps, et j'aimerai savoir commer builder ce projet sous xubuntu 18.04.
Cordialement

**Comment by nicho92** [comment]
Bonjour, @tturlin tout le build s’effectue via Maven. 
Il te faudra également GIT pour récupérer le dépôt de source
et un JDK (11) de préférence.

As tu déjà tout ces éléments ?

**Comment by tturlin** [comment]
Il me manque maven et jdk11, je les installe de suite.

**Comment by tturlin** [comment]
Ok, j'ai tout ce qu'il faut et j'ai cloner le dépot. Que dois-je faire désormais.

**Comment by nicho92** [comment]
Si maven est installé et MAVEN_HOME configuré dans le path ( $MAVEN_HOME/bin).

il faut aller dans le répertoire racine du dépôt (là où se trouve le fichier pom.xml ) et taper la commande : 

> mvn install -DskipTests

l'executable sera dans /target/executable/bin

**Comment by tturlin** [comment]
Voici le retour du build, puisque celui recontre une erreur

mvn install -DskipTests
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.magic:magic-api:jar:2.2
[WARNING] 'dependencies.dependency.systemPath' for rita-api:rita-api:jar should not point at files within the project directory, ${project.basedir}/lib/rita.jar will be unresolvable by dependent projects @ line 41, column 16
[WARNING] 'dependencies.dependency.systemPath' for mkm-api:mkm-api:jar should not point at files within the project directory, ${project.basedir}/lib/mkm-api-java-0.9.4.jar will be unresolvable by dependent projects @ line 48, column 16
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building MagicDesktopCompanion 2.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ magic-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 531 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ magic-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 486 source files to /home/korgan/Documents/MtgDesktopCompanion/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.515 s
[INFO] Finished at: 2019-03-20T17:52:14+01:00
[INFO] Final Memory: 16M/212M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project magic-api: Fatal error compiling: invalid target release: 10 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by nicho92** [comment]
> invalid target release: 10 

je pense que le $JAVA_HOME pointe sur une autre VM. (en général par defaut c'est openJDK8.
essai de taper la commande : 

> java -version

2 choix : 
soit revoir la position de java dans le $PATH
soit modifier les lignes dans le pom.xml 

> 		<maven.compiler.source>10</maven.compiler.source>
> 		<maven.compiler.target>10</maven.compiler.target>
par
> 		<maven.compiler.source>1.8</maven.compiler.source>
> 		<maven.compiler.target>18</maven.compiler.target>

**Comment by tturlin** [comment]
merci, ubuntu n'avais pas basculer sur le jdk11 quand je l'ai installé.
