### ISSUE TITLE
Format de deck pour le Commander

### ISSUE THREAD

**Issue by tturlin** [nicho92/MtgDesktopCompanion#51]
Serait-il possible d'ajouter une configuration de deck pour le format commander (singleton 99 cartes sauf basic land + 1 commandant ) ?

**Comment by nicho92** [comment]
Qu'entend tu par "configuration de deck" ? 
un écran spécifique pour créer un deck commander ?
un élément qui indique si le deck est compatible commander ?

**Comment by tturlin** [comment]
Sur l'écran de creation de deck il y a un choix pour vintage legacy standard et modern mais pas pour commander, et il peut etre qu'un champ spécifique pour le commandant serait utile, a défaut de sideboard

**Comment by nicho92** [comment]
Ces bouton ne servent que pour le filtrage des cartes compatible avec le format dans le moteur de recherche. Je viens de rajouter dans le commit af9d2397b46de94a917a8a3edb35a4709f2d4b82 la possibilité de filtrer également au format Commander.

Je vois pour également rajouter des fonctionnalités complémentaires ( indiquer le commander du deck, vérifier l'unicité des cartes).

**Comment by tturlin** [comment]
Merci beaucoup
