### ISSUE TITLE
How to run on Windows ?

### ISSUE THREAD

**Issue by Granipouss** [nicho92/MtgDesktopCompanion#62]
Hi,
The project seems very interesting, but I cannot seem to run it.
I dowloaded the 2.6 release and tried to lauch every bat file in the bin folder, they all give me the very same error. "A JNI error has occured, please check you installation and try again."
I hav not seem anything about installation in the documentation and I am not familiar (like at all) with Java. Can you help me ?

**Comment by nicho92** [comment]
Hi, 

can you tell me wich version of java do you use ? (in a command line : java -version) .

I suggest to use last version : 
[https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html](https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html)


Thanks for your feedback

**Comment by Granipouss** [comment]
I have this version:
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) Client VM (build 25.201-b09, mixed mode)  
```
I installd JDK 12.0.1 but nothing changed

**Comment by nicho92** [comment]
i suggest you to remove 1.8 java from your system.
now if you type "java -version" you have "java 12" ?

if the error persist, 

you can edit mtgdesktopcompanion.bat file with text editor at line 85 :

change
`exec "$JAVACMD" $JAVA_OPTS -XX:+UseStringDeduplication  -Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2" \ `

by

`exec "$JAVACMD" $JAVA_OPTS -Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2" \`

**Comment by Granipouss** [comment]
If I remov all Java 8 versions, I get:
```
Error: opening registry key 'Software\JavaSoft\Java Runtime Environment'
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment. 
```

It seems like the Java SDK does not install any java of their own. Plus th highest Java I cold fin on the internet was 1.8.0_211 and not 12.

I also tried to remove the options but it changed nothing

**Comment by nicho92** [comment]
I think you have problems with your java setup, maybe this thread can help you [https://stackoverflow.com/questions/6362037/java-error-opening-registry-key](https://stackoverflow.com/questions/6362037/java-error-opening-registry-key)


> Plus th highest Java I cold fin on the internet was 1.8.0_211 and not 12.
here it is : https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html

**Comment by Granipouss** [comment]
I had to add the new path to java into `PATH` and it worked just fine. Thank you :D
