### ISSUE TITLE
Scryfall error when loading all cards from set

### ISSUE THREAD

**Issue by nicho92** [nicho92/MtgDesktopCompanion#67]
Provider : Scryfall
DAO : MariaDB
UI : CollectionPanel 

Click on edition. Loading all cards from set 
LogError sample : 
https://api.scryfall.com/cards/search?q=+%2B%2B%21%22Wolfrider%27s+Saddle%22%20include:extras%20-s:m20

https://api.scryfall.com/cards/search?q=+%2B%2B%21%22Yarok%2C+the+Desecrated%22%20include:extras%20-s:m20

https://api.scryfall.com/cards/search?q=+%2B%2B%21%22Armored+Wolf-Rider%22%20include:extras%20-s:dgm

**Comment by sirrion1** [comment]
the new link to see the card from set is https://api.scryfall.com/cards/search?q=+%2B%2B!%22Wolfrider%27s+Saddle%22%20e:m20 only needs to change "include:extras" for an "e"
