### ISSUE TITLE
Init GUI: News

### ISSUE THREAD

**Issue by todotson** [nicho92/MtgDesktopCompanion#71]
Hey,

My windows batch file is stuck when I try to launch. 
![MTG1](https://user-images.githubusercontent.com/10967335/65065511-8e542100-d950-11e9-9104-ee31a2aeefd7.PNG)

**Comment by todotson** [comment]
Java 13 JDK is installed.

**Comment by nicho92** [comment]
hello, I reproduced the error with jdk13.

Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/sun/net/ssl/internal/ssl/Provider

I'm on it.

**Comment by nicho92** [comment]
Error with org.fit.cssbox.swingbox.BrowserPane

**Comment by todotson** [comment]
Thanks!
