### ISSUE TITLE
MacOS: Augmentation de la mémoire à 2048M de la JVM

### ISSUE THREAD

**Issue by Armgd** [nicho92/MtgDesktopCompanion#72]
Bonjour,
Avec les paramètres de la JVM dans mtg-desktop-companion.sh par défaut (1128M), j'ai une erreur de ce type lors de la compilation du software: 
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space

Solution, ligne 120 de mtg-desktop-companion.sh, j'ai remplacé par ceci après avoir compilé depuis la source.

`exec "$JAVACMD" $JAVA_OPTS -Xmx2048m -Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2" -Djava.library.path="./natives" \`

Java version 13+33 (OpenJDK)
MacOS 10.14.6

Si ça peut aider certains

**Comment by nicho92** [comment]
Merci pour le retour ;)

**Comment by nicho92** [comment]
Fixé par défaut 2b02023c1823f5e91286f22fc7ff6b5dc003022d
