### ISSUE TITLE
Looking for format to use for csv import

### ISSUE THREAD

**Issue by Brolmeel** [nicho92/MtgDesktopCompanion#75]
Looking for format to use for csv import. How can I know what the table headers are to import my stock

**Comment by nicho92** [comment]
Hi Brolmeel.
You need cardName / Qty / Setcode

here is a sample : 
[export.txt](https://github.com/nicho92/MtgDesktopCompanion/files/3933650/export.txt)

**Comment by nicho92** [comment]
this plugin will be updated in next version
