### ISSUE TITLE
Deckbox import does not check collector number

### ISSUE THREAD

**Issue by Brolmeel** [nicho92/MtgDesktopCompanion#79]
Deckbox import does not check collector number, only card name.

eg import of

1,1,Foulmire Knight,Throne of Eldraine,90,Near Mint,,,,,,,,,0

gets imported as alternate art with collection number 286

**Comment by nicho92** [comment]
modify DeckBoxExport.java line 150

**Comment by nicho92** [comment]
DeckboxExport is now 2.0. fixed in 8ec71a4558f647ce75be12eea6928e3a915eb060
