### ISSUE TITLE
How can I sync my stock with Library

### ISSUE THREAD

**Issue by Brolmeel** [nicho92/MtgDesktopCompanion#80]
I import my card collection via Stock import.
I assign my stock cards to Collection "Library"
Then I check Collections - Library, cards are not added.
How can I sync my stock to my Library?

**Comment by Brolmeel** [comment]
Suggestion : in the "Collection" interface when right-click a collection Sync with Stockadd an item "Sync with Stock". ( this should add cards in CARDS table for missing or update the field 'Collection' in Cards Table to 'move' it to Collection view.

**Comment by Brolmeel** [comment]
![image](https://user-images.githubusercontent.com/21075655/70535392-51698600-1b5d-11ea-8cd7-72d215f48db5.png)

**Comment by nicho92** [comment]
It seems a good idea... 
I'll work on it.

**Comment by Brolmeel** [comment]
I added it, but quick & dirty way

**Comment by Brolmeel** [comment]
How I do it : 
First I import all cards from an edition into "Missing" collection. eg all cards from Eldraine in missing.

Then with the quick and dirty button I run sync that is basically an sql update  : update cards set collection= "Collection" where ID IN ( SELECT distinct IDMC FROM STOCKS )"

That way they appear in my Collection and disappear in the Missing view
