### ISSUE TITLE
Request : Decked Builder CSV Import to Stock

### ISSUE THREAD

**Issue by Brolmeel** [nicho92/MtgDesktopCompanion#91]
request to add support for "Decked Builder" csv import into Stock

Example file uploaded (renamed to txt) :
[ELD.txt](https://github.com/nicho92/MtgDesktopCompanion/files/4175885/ELD.txt)

Cards are uniquely identified by the MVID column (multiverse id from the json db) to differentiate eg full art version, etc

**Comment by Brolmeel** [comment]
Thanks for implementing this. Really only need few columns like RegQty, FoilQty and the card ID. The rest (like pricing) MtgDeskCompanion does better job :-)

**Comment by Brolmeel** [comment]
Hmm seems like the Mvid colums does not related to mtgjson dabatase

**Comment by nicho92** [comment]
still not yet available, i just finished the structure. 
I it will be avalaible tomorrow for github ;)

**Comment by Brolmeel** [comment]
I know, but I checked my ELD.csv and the column Mvid does not relate to a card in mtgjson.
It seems to be just an internal number of the Decked Builder program, making the export useless for proper import as it does not differentiate cards with different layout like Murderous Rider.

**Comment by nicho92** [comment]
Well seen ... I was tearing my hair out .. I couldn't find any of these codes... so import will use name
