### ISSUE TITLE
Question : reset stock ID

### ISSUE THREAD

**Issue by Brolmeel** [nicho92/MtgDesktopCompanion#92]
I wonder where I can reset my stock ID when I want to restart testing stock 

![image](https://user-images.githubusercontent.com/21075655/74100026-58475180-4b2a-11ea-94a4-01e123b5638e.png)

**Comment by nicho92** [comment]
Can you tell me how do you want to use this function ?

**Comment by Brolmeel** [comment]
If I delete all my stock and then add a new card, it will start at 9204; not 1; but it is just cosmetics I guess :-)

**Comment by nicho92** [comment]
Mmh... i can't, i'm using autoincrement id from the DAO .
