### ISSUE TITLE
Bug - remove cards present in ... with adventure cards

### ISSUE THREAD

**Issue by Brolmeel** [nicho92/MtgDesktopCompanion#94]
When using "Remove cards present in Needed" in collection, it removes the creature card from the Needed, but not the Adventure card.

Example : Ardenvale Tactician is removed, Dizzying Swoop is still in Needed

![image](https://user-images.githubusercontent.com/21075655/74195301-38637b00-4c5b-11ea-92bc-b9f40c386353.png)

**Comment by sirrion1** [comment]
I try to reproduce the bug but when i click into Remove cards present in Needed all in needed is delete for me works
