### ISSUE TITLE
Bug Cardkingdom pricer

### ISSUE THREAD

**Issue by Brolmeel** [nicho92/MtgDesktopCompanion#95]
When selecting  a revised card ( eg Atog ) is looks at shadows-over-inistrad url for pricing :

![image](https://user-images.githubusercontent.com/21075655/74281243-66f65a00-4d1e-11ea-9a19-2921cc9cd6c2.png)

**Comment by Brolmeel** [comment]
Also for other older sets eg 6th : 
![image](https://user-images.githubusercontent.com/21075655/74282368-4e873f00-4d20-11ea-8954-4dd3e9f7a4ea.png)

**Comment by nicho92** [comment]
bugfixed the 2 sets. 
waiting to find better Set recognition...
